load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "consumer_lib",
    srcs = ["main.go"],
    importpath = "github.com/owlmq/owlmq/examples/usage_01/consumer",
    visibility = ["//visibility:private"],
    deps = [
        "//api/owlmq",
        "@org_golang_google_grpc//:go_default_library",
    ],
)

go_binary(
    name = "consumer",
    embed = [":consumer_lib"],
    visibility = ["//visibility:public"],
)
