load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "chord",
    srcs = [
        "between.go",
        "chord.go",
        "fingertable.go",
        "get.go",
        "put.go",
        "stabilize.go",
    ],
    importpath = "github.com/owlmq/owlmq/chord",
    visibility = ["//visibility:public"],
    deps = [
        "//api/owlmq",
        "//config",
        "//crypto",
        "//replicator",
        "//storage",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials/insecure",
    ],
)
