// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: organisation.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrganisationIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganisationIDRequest) Reset() {
	*x = OrganisationIDRequest{}
	mi := &file_organisation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganisationIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganisationIDRequest) ProtoMessage() {}

func (x *OrganisationIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organisation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganisationIDRequest.ProtoReflect.Descriptor instead.
func (*OrganisationIDRequest) Descriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{0}
}

func (x *OrganisationIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OrganisationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganisationResponse) Reset() {
	*x = OrganisationResponse{}
	mi := &file_organisation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganisationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganisationResponse) ProtoMessage() {}

func (x *OrganisationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organisation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganisationResponse.ProtoReflect.Descriptor instead.
func (*OrganisationResponse) Descriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{1}
}

func (x *OrganisationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrganisationResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_organisation_proto protoreflect.FileDescriptor

var file_organisation_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x27, 0x0a, 0x15, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3a, 0x0a, 0x14, 0x4f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x6e, 0x0a, 0x0a, 0x4f, 0x72, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x12, 0x23, 0x2e, 0x6f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_organisation_proto_rawDescOnce sync.Once
	file_organisation_proto_rawDescData = file_organisation_proto_rawDesc
)

func file_organisation_proto_rawDescGZIP() []byte {
	file_organisation_proto_rawDescOnce.Do(func() {
		file_organisation_proto_rawDescData = protoimpl.X.CompressGZIP(file_organisation_proto_rawDescData)
	})
	return file_organisation_proto_rawDescData
}

var file_organisation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_organisation_proto_goTypes = []any{
	(*OrganisationIDRequest)(nil), // 0: organisation.OrganisationIDRequest
	(*OrganisationResponse)(nil),  // 1: organisation.OrganisationResponse
}
var file_organisation_proto_depIdxs = []int32{
	0, // 0: organisation.OrgService.GetOrganisationByID:input_type -> organisation.OrganisationIDRequest
	1, // 1: organisation.OrgService.GetOrganisationByID:output_type -> organisation.OrganisationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_organisation_proto_init() }
func file_organisation_proto_init() {
	if File_organisation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_organisation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_organisation_proto_goTypes,
		DependencyIndexes: file_organisation_proto_depIdxs,
		MessageInfos:      file_organisation_proto_msgTypes,
	}.Build()
	File_organisation_proto = out.File
	file_organisation_proto_rawDesc = nil
	file_organisation_proto_goTypes = nil
	file_organisation_proto_depIdxs = nil
}
