syntax = "proto3";
//import "google/protobuf/empty.proto";
option go_package  = "/owlmq";
package api_owlmq;

// This file holds the description of the outside api of owlmq
//enum Role {
  //ROLE_NOROLE = 0;
  //ROLE_USER = 1;
  //ROLE_NODE = 2;
  //ROLE_ADMIN = 3;
//}

//message RoleBasedAccessControl {
  //repeated Role allowed_roles = 1;
  //bool allow_unauthenticated = 2;
//}

//extend google.protobuf.MethodOptions {
  //optional RoleBasedAccessControl access_control = 90000;
//}

service Owlmq {
  //##################
  //###   cluster  ###
  //##################
  //rpc NodeJoin() returns () {
    //option (components.rbac.v1.access_control) = {
      //allowed_roles: [ROLE_NODE]
      //allow_unauthenticated: false
    //};
  //};
  rpc NodeJoin(NodeJoinRequest) returns (NodeJoinResponse);
  //rpc NodeLeave() returns ();
  rpc NodeList(NodeListRequest) returns (NodeListResponse);
  rpc FindSuccessor(FindSuccessorRequest) returns (FindSuccessorResponse);

  rpc Ping(PingRequest) returns (PingResponse);
  rpc GetPredecessor(GetPredecessorRequest) returns (GetPredecessorResponse);
  rpc GetSuccessor(GetSuccessorRequest) returns (GetSuccessorResponse);
  rpc SetPredecessor(SetPredecessorRequest) returns (SetPredecessorResponse);
  rpc SetSuccessor(SetSuccessorRequest) returns (SetSuccessorResponse);

  //###################
  //###    auth     ###
  //###################
  //rpc UserRegister() returns ();
  //rpc UserDelete() returns ();
  //rpc UserList() returns ();

  //##############################
  //###    key-value store     ###
  //##############################
  rpc Get(KV_GetRequest) returns (KV_GetResponse);
  rpc Put(KV_PutRequest) returns (KV_PutResponse);
}

//##################
//###   cluster  ###
//##################
message PingRequest {}
message PingResponse {}

enum NODEJOIN_STATUS {
  NJ_SUCCESS = 0;
  NJ_FAILURE = 1;
}
message NodeJoinRequest { string address = 1; }
message NodeJoinResponse {
  NODEJOIN_STATUS status = 1;
  string errorMsg = 2;
}

message NodeListRequest {}

message NodeListResponse {
  string successor = 1;
  string predecessor = 2;
  repeated string knownNodes = 3;
}

message FindSuccessorRequest { bytes hash = 1; }
message FindSuccessorResponse { string address = 1; }

message GetPredecessorRequest {}
message GetPredecessorResponse { string address = 1; }

message GetSuccessorRequest {}
message GetSuccessorResponse { string address = 1; }

message SetPredecessorRequest { string address = 1; }
message SetPredecessorResponse {}

message SetSuccessorRequest { string address = 1; }
message SetSuccessorResponse {}

//##############################
//###    key-value store     ###
//##############################
enum KV_STATUS {
  KV_SUCCESS = 0;
  KV_FAILURE = 1;
}

message KV_GetRequest {
  string key = 1;
}

message KV_GetResponse {
  KV_STATUS status = 1;
  string value = 2;
  string errorMsg = 3;
}

message KV_PutRequest {
  string key = 1;
  string value = 2;
}

message KV_PutResponse {
  KV_STATUS status = 1;
  string errorMsg = 2;
}
