// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: owlmq/owlmq.proto

package owlmq

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Owlmq_NodeJoin_FullMethodName        = "/api_owlmq.Owlmq/NodeJoin"
	Owlmq_NodeList_FullMethodName        = "/api_owlmq.Owlmq/NodeList"
	Owlmq_FindSuccessor_FullMethodName   = "/api_owlmq.Owlmq/FindSuccessor"
	Owlmq_Ping_FullMethodName            = "/api_owlmq.Owlmq/Ping"
	Owlmq_GetPredecessor_FullMethodName  = "/api_owlmq.Owlmq/GetPredecessor"
	Owlmq_GetSuccessor_FullMethodName    = "/api_owlmq.Owlmq/GetSuccessor"
	Owlmq_SetPredecessor_FullMethodName  = "/api_owlmq.Owlmq/SetPredecessor"
	Owlmq_SetSuccessor_FullMethodName    = "/api_owlmq.Owlmq/SetSuccessor"
	Owlmq_GetReplicaEntry_FullMethodName = "/api_owlmq.Owlmq/GetReplicaEntry"
	Owlmq_PutReplicaEntry_FullMethodName = "/api_owlmq.Owlmq/PutReplicaEntry"
	Owlmq_Get_FullMethodName             = "/api_owlmq.Owlmq/Get"
	Owlmq_Put_FullMethodName             = "/api_owlmq.Owlmq/Put"
	Owlmq_ProduceOne_FullMethodName      = "/api_owlmq.Owlmq/ProduceOne"
	Owlmq_Produce_FullMethodName         = "/api_owlmq.Owlmq/Produce"
	Owlmq_ConsumeOne_FullMethodName      = "/api_owlmq.Owlmq/ConsumeOne"
	Owlmq_Consume_FullMethodName         = "/api_owlmq.Owlmq/Consume"
	Owlmq_NewQueue_FullMethodName        = "/api_owlmq.Owlmq/NewQueue"
	Owlmq_Ack_FullMethodName             = "/api_owlmq.Owlmq/Ack"
)

// OwlmqClient is the client API for Owlmq service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OwlmqClient interface {
	// ##################
	// ###   cluster  ###
	// ##################
	// rpc NodeJoin() returns () {
	// option (components.rbac.v1.access_control) = {
	// allowed_roles: [ROLE_NODE]
	// allow_unauthenticated: false
	// };
	// };
	NodeJoin(ctx context.Context, in *NodeJoinRequest, opts ...grpc.CallOption) (*NodeJoinResponse, error)
	// rpc NodeLeave() returns ();
	NodeList(ctx context.Context, in *NodeListRequest, opts ...grpc.CallOption) (*NodeListResponse, error)
	FindSuccessor(ctx context.Context, in *FindSuccessorRequest, opts ...grpc.CallOption) (*FindSuccessorResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	GetPredecessor(ctx context.Context, in *GetPredecessorRequest, opts ...grpc.CallOption) (*GetPredecessorResponse, error)
	GetSuccessor(ctx context.Context, in *GetSuccessorRequest, opts ...grpc.CallOption) (*GetSuccessorResponse, error)
	SetPredecessor(ctx context.Context, in *SetPredecessorRequest, opts ...grpc.CallOption) (*SetPredecessorResponse, error)
	SetSuccessor(ctx context.Context, in *SetSuccessorRequest, opts ...grpc.CallOption) (*SetSuccessorResponse, error)
	// ##############################
	// ###      replication       ###
	// ##############################
	GetReplicaEntry(ctx context.Context, in *ReplicaGetRequest, opts ...grpc.CallOption) (*ReplicaGetResponse, error)
	PutReplicaEntry(ctx context.Context, in *ReplicaPutRequest, opts ...grpc.CallOption) (*ReplicaPutResponse, error)
	// ##############################
	// ###    key-value store     ###
	// ##############################
	Get(ctx context.Context, in *KV_GetRequest, opts ...grpc.CallOption) (*KV_GetResponse, error)
	Put(ctx context.Context, in *KV_PutRequest, opts ...grpc.CallOption) (*KV_PutResponse, error)
	// ##############################
	// ###       messaging        ###
	// ##############################
	ProduceOne(ctx context.Context, in *Message, opts ...grpc.CallOption) (*ProduceOneResponse, error)
	Produce(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Message, ProduceResponse], error)
	ConsumeOne(ctx context.Context, in *ConsumeOneRequest, opts ...grpc.CallOption) (*Message, error)
	Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Message], error)
	NewQueue(ctx context.Context, in *NewQueueRequest, opts ...grpc.CallOption) (*NewQueueResponse, error)
	Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error)
}

type owlmqClient struct {
	cc grpc.ClientConnInterface
}

func NewOwlmqClient(cc grpc.ClientConnInterface) OwlmqClient {
	return &owlmqClient{cc}
}

func (c *owlmqClient) NodeJoin(ctx context.Context, in *NodeJoinRequest, opts ...grpc.CallOption) (*NodeJoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeJoinResponse)
	err := c.cc.Invoke(ctx, Owlmq_NodeJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlmqClient) NodeList(ctx context.Context, in *NodeListRequest, opts ...grpc.CallOption) (*NodeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeListResponse)
	err := c.cc.Invoke(ctx, Owlmq_NodeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlmqClient) FindSuccessor(ctx context.Context, in *FindSuccessorRequest, opts ...grpc.CallOption) (*FindSuccessorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindSuccessorResponse)
	err := c.cc.Invoke(ctx, Owlmq_FindSuccessor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlmqClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Owlmq_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlmqClient) GetPredecessor(ctx context.Context, in *GetPredecessorRequest, opts ...grpc.CallOption) (*GetPredecessorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPredecessorResponse)
	err := c.cc.Invoke(ctx, Owlmq_GetPredecessor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlmqClient) GetSuccessor(ctx context.Context, in *GetSuccessorRequest, opts ...grpc.CallOption) (*GetSuccessorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSuccessorResponse)
	err := c.cc.Invoke(ctx, Owlmq_GetSuccessor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlmqClient) SetPredecessor(ctx context.Context, in *SetPredecessorRequest, opts ...grpc.CallOption) (*SetPredecessorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPredecessorResponse)
	err := c.cc.Invoke(ctx, Owlmq_SetPredecessor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlmqClient) SetSuccessor(ctx context.Context, in *SetSuccessorRequest, opts ...grpc.CallOption) (*SetSuccessorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSuccessorResponse)
	err := c.cc.Invoke(ctx, Owlmq_SetSuccessor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlmqClient) GetReplicaEntry(ctx context.Context, in *ReplicaGetRequest, opts ...grpc.CallOption) (*ReplicaGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicaGetResponse)
	err := c.cc.Invoke(ctx, Owlmq_GetReplicaEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlmqClient) PutReplicaEntry(ctx context.Context, in *ReplicaPutRequest, opts ...grpc.CallOption) (*ReplicaPutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicaPutResponse)
	err := c.cc.Invoke(ctx, Owlmq_PutReplicaEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlmqClient) Get(ctx context.Context, in *KV_GetRequest, opts ...grpc.CallOption) (*KV_GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KV_GetResponse)
	err := c.cc.Invoke(ctx, Owlmq_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlmqClient) Put(ctx context.Context, in *KV_PutRequest, opts ...grpc.CallOption) (*KV_PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KV_PutResponse)
	err := c.cc.Invoke(ctx, Owlmq_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlmqClient) ProduceOne(ctx context.Context, in *Message, opts ...grpc.CallOption) (*ProduceOneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProduceOneResponse)
	err := c.cc.Invoke(ctx, Owlmq_ProduceOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlmqClient) Produce(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Message, ProduceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Owlmq_ServiceDesc.Streams[0], Owlmq_Produce_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Message, ProduceResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Owlmq_ProduceClient = grpc.ClientStreamingClient[Message, ProduceResponse]

func (c *owlmqClient) ConsumeOne(ctx context.Context, in *ConsumeOneRequest, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, Owlmq_ConsumeOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlmqClient) Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Owlmq_ServiceDesc.Streams[1], Owlmq_Consume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsumeRequest, Message]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Owlmq_ConsumeClient = grpc.ServerStreamingClient[Message]

func (c *owlmqClient) NewQueue(ctx context.Context, in *NewQueueRequest, opts ...grpc.CallOption) (*NewQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewQueueResponse)
	err := c.cc.Invoke(ctx, Owlmq_NewQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlmqClient) Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, Owlmq_Ack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OwlmqServer is the server API for Owlmq service.
// All implementations must embed UnimplementedOwlmqServer
// for forward compatibility.
type OwlmqServer interface {
	// ##################
	// ###   cluster  ###
	// ##################
	// rpc NodeJoin() returns () {
	// option (components.rbac.v1.access_control) = {
	// allowed_roles: [ROLE_NODE]
	// allow_unauthenticated: false
	// };
	// };
	NodeJoin(context.Context, *NodeJoinRequest) (*NodeJoinResponse, error)
	// rpc NodeLeave() returns ();
	NodeList(context.Context, *NodeListRequest) (*NodeListResponse, error)
	FindSuccessor(context.Context, *FindSuccessorRequest) (*FindSuccessorResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	GetPredecessor(context.Context, *GetPredecessorRequest) (*GetPredecessorResponse, error)
	GetSuccessor(context.Context, *GetSuccessorRequest) (*GetSuccessorResponse, error)
	SetPredecessor(context.Context, *SetPredecessorRequest) (*SetPredecessorResponse, error)
	SetSuccessor(context.Context, *SetSuccessorRequest) (*SetSuccessorResponse, error)
	// ##############################
	// ###      replication       ###
	// ##############################
	GetReplicaEntry(context.Context, *ReplicaGetRequest) (*ReplicaGetResponse, error)
	PutReplicaEntry(context.Context, *ReplicaPutRequest) (*ReplicaPutResponse, error)
	// ##############################
	// ###    key-value store     ###
	// ##############################
	Get(context.Context, *KV_GetRequest) (*KV_GetResponse, error)
	Put(context.Context, *KV_PutRequest) (*KV_PutResponse, error)
	// ##############################
	// ###       messaging        ###
	// ##############################
	ProduceOne(context.Context, *Message) (*ProduceOneResponse, error)
	Produce(grpc.ClientStreamingServer[Message, ProduceResponse]) error
	ConsumeOne(context.Context, *ConsumeOneRequest) (*Message, error)
	Consume(*ConsumeRequest, grpc.ServerStreamingServer[Message]) error
	NewQueue(context.Context, *NewQueueRequest) (*NewQueueResponse, error)
	Ack(context.Context, *AckRequest) (*AckResponse, error)
	mustEmbedUnimplementedOwlmqServer()
}

// UnimplementedOwlmqServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOwlmqServer struct{}

func (UnimplementedOwlmqServer) NodeJoin(context.Context, *NodeJoinRequest) (*NodeJoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeJoin not implemented")
}
func (UnimplementedOwlmqServer) NodeList(context.Context, *NodeListRequest) (*NodeListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeList not implemented")
}
func (UnimplementedOwlmqServer) FindSuccessor(context.Context, *FindSuccessorRequest) (*FindSuccessorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindSuccessor not implemented")
}
func (UnimplementedOwlmqServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedOwlmqServer) GetPredecessor(context.Context, *GetPredecessorRequest) (*GetPredecessorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPredecessor not implemented")
}
func (UnimplementedOwlmqServer) GetSuccessor(context.Context, *GetSuccessorRequest) (*GetSuccessorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuccessor not implemented")
}
func (UnimplementedOwlmqServer) SetPredecessor(context.Context, *SetPredecessorRequest) (*SetPredecessorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPredecessor not implemented")
}
func (UnimplementedOwlmqServer) SetSuccessor(context.Context, *SetSuccessorRequest) (*SetSuccessorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSuccessor not implemented")
}
func (UnimplementedOwlmqServer) GetReplicaEntry(context.Context, *ReplicaGetRequest) (*ReplicaGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReplicaEntry not implemented")
}
func (UnimplementedOwlmqServer) PutReplicaEntry(context.Context, *ReplicaPutRequest) (*ReplicaPutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutReplicaEntry not implemented")
}
func (UnimplementedOwlmqServer) Get(context.Context, *KV_GetRequest) (*KV_GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedOwlmqServer) Put(context.Context, *KV_PutRequest) (*KV_PutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedOwlmqServer) ProduceOne(context.Context, *Message) (*ProduceOneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProduceOne not implemented")
}
func (UnimplementedOwlmqServer) Produce(grpc.ClientStreamingServer[Message, ProduceResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Produce not implemented")
}
func (UnimplementedOwlmqServer) ConsumeOne(context.Context, *ConsumeOneRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsumeOne not implemented")
}
func (UnimplementedOwlmqServer) Consume(*ConsumeRequest, grpc.ServerStreamingServer[Message]) error {
	return status.Errorf(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedOwlmqServer) NewQueue(context.Context, *NewQueueRequest) (*NewQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewQueue not implemented")
}
func (UnimplementedOwlmqServer) Ack(context.Context, *AckRequest) (*AckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ack not implemented")
}
func (UnimplementedOwlmqServer) mustEmbedUnimplementedOwlmqServer() {}
func (UnimplementedOwlmqServer) testEmbeddedByValue()               {}

// UnsafeOwlmqServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OwlmqServer will
// result in compilation errors.
type UnsafeOwlmqServer interface {
	mustEmbedUnimplementedOwlmqServer()
}

func RegisterOwlmqServer(s grpc.ServiceRegistrar, srv OwlmqServer) {
	// If the following call pancis, it indicates UnimplementedOwlmqServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Owlmq_ServiceDesc, srv)
}

func _Owlmq_NodeJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).NodeJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_NodeJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).NodeJoin(ctx, req.(*NodeJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Owlmq_NodeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).NodeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_NodeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).NodeList(ctx, req.(*NodeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Owlmq_FindSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindSuccessorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).FindSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_FindSuccessor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).FindSuccessor(ctx, req.(*FindSuccessorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Owlmq_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Owlmq_GetPredecessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPredecessorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).GetPredecessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_GetPredecessor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).GetPredecessor(ctx, req.(*GetPredecessorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Owlmq_GetSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSuccessorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).GetSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_GetSuccessor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).GetSuccessor(ctx, req.(*GetSuccessorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Owlmq_SetPredecessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPredecessorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).SetPredecessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_SetPredecessor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).SetPredecessor(ctx, req.(*SetPredecessorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Owlmq_SetSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSuccessorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).SetSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_SetSuccessor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).SetSuccessor(ctx, req.(*SetSuccessorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Owlmq_GetReplicaEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).GetReplicaEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_GetReplicaEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).GetReplicaEntry(ctx, req.(*ReplicaGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Owlmq_PutReplicaEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).PutReplicaEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_PutReplicaEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).PutReplicaEntry(ctx, req.(*ReplicaPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Owlmq_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KV_GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).Get(ctx, req.(*KV_GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Owlmq_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KV_PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).Put(ctx, req.(*KV_PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Owlmq_ProduceOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).ProduceOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_ProduceOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).ProduceOne(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Owlmq_Produce_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OwlmqServer).Produce(&grpc.GenericServerStream[Message, ProduceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Owlmq_ProduceServer = grpc.ClientStreamingServer[Message, ProduceResponse]

func _Owlmq_ConsumeOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).ConsumeOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_ConsumeOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).ConsumeOne(ctx, req.(*ConsumeOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Owlmq_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConsumeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OwlmqServer).Consume(m, &grpc.GenericServerStream[ConsumeRequest, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Owlmq_ConsumeServer = grpc.ServerStreamingServer[Message]

func _Owlmq_NewQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).NewQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_NewQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).NewQueue(ctx, req.(*NewQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Owlmq_Ack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).Ack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_Ack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).Ack(ctx, req.(*AckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Owlmq_ServiceDesc is the grpc.ServiceDesc for Owlmq service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Owlmq_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api_owlmq.Owlmq",
	HandlerType: (*OwlmqServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NodeJoin",
			Handler:    _Owlmq_NodeJoin_Handler,
		},
		{
			MethodName: "NodeList",
			Handler:    _Owlmq_NodeList_Handler,
		},
		{
			MethodName: "FindSuccessor",
			Handler:    _Owlmq_FindSuccessor_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Owlmq_Ping_Handler,
		},
		{
			MethodName: "GetPredecessor",
			Handler:    _Owlmq_GetPredecessor_Handler,
		},
		{
			MethodName: "GetSuccessor",
			Handler:    _Owlmq_GetSuccessor_Handler,
		},
		{
			MethodName: "SetPredecessor",
			Handler:    _Owlmq_SetPredecessor_Handler,
		},
		{
			MethodName: "SetSuccessor",
			Handler:    _Owlmq_SetSuccessor_Handler,
		},
		{
			MethodName: "GetReplicaEntry",
			Handler:    _Owlmq_GetReplicaEntry_Handler,
		},
		{
			MethodName: "PutReplicaEntry",
			Handler:    _Owlmq_PutReplicaEntry_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Owlmq_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Owlmq_Put_Handler,
		},
		{
			MethodName: "ProduceOne",
			Handler:    _Owlmq_ProduceOne_Handler,
		},
		{
			MethodName: "ConsumeOne",
			Handler:    _Owlmq_ConsumeOne_Handler,
		},
		{
			MethodName: "NewQueue",
			Handler:    _Owlmq_NewQueue_Handler,
		},
		{
			MethodName: "Ack",
			Handler:    _Owlmq_Ack_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Produce",
			Handler:       _Owlmq_Produce_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Consume",
			Handler:       _Owlmq_Consume_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "owlmq/owlmq.proto",
}
