// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: owlmq/owlmq.proto

package owlmq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ##############################
// ###    key-value store     ###
// ##############################
type KV_STATUS int32

const (
	KV_STATUS_SUCCESS KV_STATUS = 0
	KV_STATUS_FAILURE KV_STATUS = 1
)

// Enum value maps for KV_STATUS.
var (
	KV_STATUS_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
	}
	KV_STATUS_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
	}
)

func (x KV_STATUS) Enum() *KV_STATUS {
	p := new(KV_STATUS)
	*p = x
	return p
}

func (x KV_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KV_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_owlmq_owlmq_proto_enumTypes[0].Descriptor()
}

func (KV_STATUS) Type() protoreflect.EnumType {
	return &file_owlmq_owlmq_proto_enumTypes[0]
}

func (x KV_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KV_STATUS.Descriptor instead.
func (KV_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{0}
}

type FindSuccessorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSuccessorRequest) Reset() {
	*x = FindSuccessorRequest{}
	mi := &file_owlmq_owlmq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSuccessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorRequest) ProtoMessage() {}

func (x *FindSuccessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorRequest.ProtoReflect.Descriptor instead.
func (*FindSuccessorRequest) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{0}
}

func (x *FindSuccessorRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type FindSuccessorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSuccessorResponse) Reset() {
	*x = FindSuccessorResponse{}
	mi := &file_owlmq_owlmq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSuccessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorResponse) ProtoMessage() {}

func (x *FindSuccessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorResponse.ProtoReflect.Descriptor instead.
func (*FindSuccessorResponse) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{1}
}

func (x *FindSuccessorResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type KV_GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KV_GetRequest) Reset() {
	*x = KV_GetRequest{}
	mi := &file_owlmq_owlmq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KV_GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KV_GetRequest) ProtoMessage() {}

func (x *KV_GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KV_GetRequest.ProtoReflect.Descriptor instead.
func (*KV_GetRequest) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{2}
}

func (x *KV_GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KV_GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        KV_STATUS              `protobuf:"varint,1,opt,name=status,proto3,enum=api_owlmq.KV_STATUS" json:"status,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KV_GetResponse) Reset() {
	*x = KV_GetResponse{}
	mi := &file_owlmq_owlmq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KV_GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KV_GetResponse) ProtoMessage() {}

func (x *KV_GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KV_GetResponse.ProtoReflect.Descriptor instead.
func (*KV_GetResponse) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{3}
}

func (x *KV_GetResponse) GetStatus() KV_STATUS {
	if x != nil {
		return x.Status
	}
	return KV_STATUS_SUCCESS
}

func (x *KV_GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *KV_GetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type KV_PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KV_PutRequest) Reset() {
	*x = KV_PutRequest{}
	mi := &file_owlmq_owlmq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KV_PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KV_PutRequest) ProtoMessage() {}

func (x *KV_PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KV_PutRequest.ProtoReflect.Descriptor instead.
func (*KV_PutRequest) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{4}
}

func (x *KV_PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KV_PutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type KV_PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        KV_STATUS              `protobuf:"varint,1,opt,name=status,proto3,enum=api_owlmq.KV_STATUS" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KV_PutResponse) Reset() {
	*x = KV_PutResponse{}
	mi := &file_owlmq_owlmq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KV_PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KV_PutResponse) ProtoMessage() {}

func (x *KV_PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KV_PutResponse.ProtoReflect.Descriptor instead.
func (*KV_PutResponse) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{5}
}

func (x *KV_PutResponse) GetStatus() KV_STATUS {
	if x != nil {
		return x.Status
	}
	return KV_STATUS_SUCCESS
}

func (x *KV_PutResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_owlmq_owlmq_proto protoreflect.FileDescriptor

var file_owlmq_owlmq_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x14, 0x46,
	0x69, 0x6e, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x31, 0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x21, 0x0a, 0x0d, 0x4b, 0x56,
	0x5f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x6a, 0x0a,
	0x0e, 0x4b, 0x56, 0x5f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x14, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4b, 0x56, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x37, 0x0a, 0x0d, 0x4b, 0x56, 0x5f,
	0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x54, 0x0a, 0x0e, 0x4b, 0x56, 0x5f, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71,
	0x2e, 0x4b, 0x56, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2a, 0x25, 0x0a, 0x09, 0x4b, 0x56, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x01, 0x32,
	0xd3, 0x01, 0x0a, 0x05, 0x4f, 0x77, 0x6c, 0x6d, 0x71, 0x12, 0x52, 0x0a, 0x0d, 0x46, 0x69, 0x6e,
	0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69,
	0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70,
	0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a,
	0x03, 0x47, 0x65, 0x74, 0x12, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71,
	0x2e, 0x4b, 0x56, 0x5f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4b, 0x56, 0x5f, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x03, 0x50, 0x75, 0x74,
	0x12, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4b, 0x56, 0x5f,
	0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69,
	0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4b, 0x56, 0x5f, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_owlmq_owlmq_proto_rawDescOnce sync.Once
	file_owlmq_owlmq_proto_rawDescData = file_owlmq_owlmq_proto_rawDesc
)

func file_owlmq_owlmq_proto_rawDescGZIP() []byte {
	file_owlmq_owlmq_proto_rawDescOnce.Do(func() {
		file_owlmq_owlmq_proto_rawDescData = protoimpl.X.CompressGZIP(file_owlmq_owlmq_proto_rawDescData)
	})
	return file_owlmq_owlmq_proto_rawDescData
}

var file_owlmq_owlmq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_owlmq_owlmq_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_owlmq_owlmq_proto_goTypes = []any{
	(KV_STATUS)(0),                // 0: api_owlmq.KV_STATUS
	(*FindSuccessorRequest)(nil),  // 1: api_owlmq.FindSuccessorRequest
	(*FindSuccessorResponse)(nil), // 2: api_owlmq.FindSuccessorResponse
	(*KV_GetRequest)(nil),         // 3: api_owlmq.KV_GetRequest
	(*KV_GetResponse)(nil),        // 4: api_owlmq.KV_GetResponse
	(*KV_PutRequest)(nil),         // 5: api_owlmq.KV_PutRequest
	(*KV_PutResponse)(nil),        // 6: api_owlmq.KV_PutResponse
}
var file_owlmq_owlmq_proto_depIdxs = []int32{
	0, // 0: api_owlmq.KV_GetResponse.status:type_name -> api_owlmq.KV_STATUS
	0, // 1: api_owlmq.KV_PutResponse.status:type_name -> api_owlmq.KV_STATUS
	1, // 2: api_owlmq.Owlmq.FindSuccessor:input_type -> api_owlmq.FindSuccessorRequest
	3, // 3: api_owlmq.Owlmq.Get:input_type -> api_owlmq.KV_GetRequest
	5, // 4: api_owlmq.Owlmq.Put:input_type -> api_owlmq.KV_PutRequest
	2, // 5: api_owlmq.Owlmq.FindSuccessor:output_type -> api_owlmq.FindSuccessorResponse
	4, // 6: api_owlmq.Owlmq.Get:output_type -> api_owlmq.KV_GetResponse
	6, // 7: api_owlmq.Owlmq.Put:output_type -> api_owlmq.KV_PutResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_owlmq_owlmq_proto_init() }
func file_owlmq_owlmq_proto_init() {
	if File_owlmq_owlmq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_owlmq_owlmq_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_owlmq_owlmq_proto_goTypes,
		DependencyIndexes: file_owlmq_owlmq_proto_depIdxs,
		EnumInfos:         file_owlmq_owlmq_proto_enumTypes,
		MessageInfos:      file_owlmq_owlmq_proto_msgTypes,
	}.Build()
	File_owlmq_owlmq_proto = out.File
	file_owlmq_owlmq_proto_rawDesc = nil
	file_owlmq_owlmq_proto_goTypes = nil
	file_owlmq_owlmq_proto_depIdxs = nil
}
