// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: owlmq/owlmq.proto

package owlmq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ##################
// ###  messaging ###
// ##################
type MESSAGE_STATUS int32

const (
	MESSAGE_STATUS_MSG_SUCCESS MESSAGE_STATUS = 0
	MESSAGE_STATUS_MSG_FAILURE MESSAGE_STATUS = 1
)

// Enum value maps for MESSAGE_STATUS.
var (
	MESSAGE_STATUS_name = map[int32]string{
		0: "MSG_SUCCESS",
		1: "MSG_FAILURE",
	}
	MESSAGE_STATUS_value = map[string]int32{
		"MSG_SUCCESS": 0,
		"MSG_FAILURE": 1,
	}
)

func (x MESSAGE_STATUS) Enum() *MESSAGE_STATUS {
	p := new(MESSAGE_STATUS)
	*p = x
	return p
}

func (x MESSAGE_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MESSAGE_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_owlmq_owlmq_proto_enumTypes[0].Descriptor()
}

func (MESSAGE_STATUS) Type() protoreflect.EnumType {
	return &file_owlmq_owlmq_proto_enumTypes[0]
}

func (x MESSAGE_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MESSAGE_STATUS.Descriptor instead.
func (MESSAGE_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{0}
}

type NODEJOIN_STATUS int32

const (
	NODEJOIN_STATUS_NJ_SUCCESS NODEJOIN_STATUS = 0
	NODEJOIN_STATUS_NJ_FAILURE NODEJOIN_STATUS = 1
)

// Enum value maps for NODEJOIN_STATUS.
var (
	NODEJOIN_STATUS_name = map[int32]string{
		0: "NJ_SUCCESS",
		1: "NJ_FAILURE",
	}
	NODEJOIN_STATUS_value = map[string]int32{
		"NJ_SUCCESS": 0,
		"NJ_FAILURE": 1,
	}
)

func (x NODEJOIN_STATUS) Enum() *NODEJOIN_STATUS {
	p := new(NODEJOIN_STATUS)
	*p = x
	return p
}

func (x NODEJOIN_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NODEJOIN_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_owlmq_owlmq_proto_enumTypes[1].Descriptor()
}

func (NODEJOIN_STATUS) Type() protoreflect.EnumType {
	return &file_owlmq_owlmq_proto_enumTypes[1]
}

func (x NODEJOIN_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NODEJOIN_STATUS.Descriptor instead.
func (NODEJOIN_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{1}
}

// ##############################
// ###      replication       ###
// ##############################
type REPLICA_STATUS int32

const (
	REPLICA_STATUS_REPLICA_SUCCESS REPLICA_STATUS = 0
	REPLICA_STATUS_REPLICA_FAILURE REPLICA_STATUS = 1
)

// Enum value maps for REPLICA_STATUS.
var (
	REPLICA_STATUS_name = map[int32]string{
		0: "REPLICA_SUCCESS",
		1: "REPLICA_FAILURE",
	}
	REPLICA_STATUS_value = map[string]int32{
		"REPLICA_SUCCESS": 0,
		"REPLICA_FAILURE": 1,
	}
)

func (x REPLICA_STATUS) Enum() *REPLICA_STATUS {
	p := new(REPLICA_STATUS)
	*p = x
	return p
}

func (x REPLICA_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (REPLICA_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_owlmq_owlmq_proto_enumTypes[2].Descriptor()
}

func (REPLICA_STATUS) Type() protoreflect.EnumType {
	return &file_owlmq_owlmq_proto_enumTypes[2]
}

func (x REPLICA_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use REPLICA_STATUS.Descriptor instead.
func (REPLICA_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{2}
}

// ##############################
// ###    key-value store     ###
// ##############################
type KV_STATUS int32

const (
	KV_STATUS_KV_SUCCESS KV_STATUS = 0
	KV_STATUS_KV_FAILURE KV_STATUS = 1
)

// Enum value maps for KV_STATUS.
var (
	KV_STATUS_name = map[int32]string{
		0: "KV_SUCCESS",
		1: "KV_FAILURE",
	}
	KV_STATUS_value = map[string]int32{
		"KV_SUCCESS": 0,
		"KV_FAILURE": 1,
	}
)

func (x KV_STATUS) Enum() *KV_STATUS {
	p := new(KV_STATUS)
	*p = x
	return p
}

func (x KV_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KV_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_owlmq_owlmq_proto_enumTypes[3].Descriptor()
}

func (KV_STATUS) Type() protoreflect.EnumType {
	return &file_owlmq_owlmq_proto_enumTypes[3]
}

func (x KV_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KV_STATUS.Descriptor instead.
func (KV_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{3}
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TODO think about this, could be nice so that the user can set the id -> storage location on the ring
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Content       string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_owlmq_owlmq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ProduceOneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        MESSAGE_STATUS         `protobuf:"varint,1,opt,name=status,proto3,enum=api_owlmq.MESSAGE_STATUS" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceOneResponse) Reset() {
	*x = ProduceOneResponse{}
	mi := &file_owlmq_owlmq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceOneResponse) ProtoMessage() {}

func (x *ProduceOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceOneResponse.ProtoReflect.Descriptor instead.
func (*ProduceOneResponse) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{1}
}

func (x *ProduceOneResponse) GetStatus() MESSAGE_STATUS {
	if x != nil {
		return x.Status
	}
	return MESSAGE_STATUS_MSG_SUCCESS
}

type ProduceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        MESSAGE_STATUS         `protobuf:"varint,1,opt,name=status,proto3,enum=api_owlmq.MESSAGE_STATUS" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceResponse) Reset() {
	*x = ProduceResponse{}
	mi := &file_owlmq_owlmq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceResponse) ProtoMessage() {}

func (x *ProduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceResponse.ProtoReflect.Descriptor instead.
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{2}
}

func (x *ProduceResponse) GetStatus() MESSAGE_STATUS {
	if x != nil {
		return x.Status
	}
	return MESSAGE_STATUS_MSG_SUCCESS
}

type ConsumeOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId    string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeOneRequest) Reset() {
	*x = ConsumeOneRequest{}
	mi := &file_owlmq_owlmq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeOneRequest) ProtoMessage() {}

func (x *ConsumeOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeOneRequest.ProtoReflect.Descriptor instead.
func (*ConsumeOneRequest) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{3}
}

func (x *ConsumeOneRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type ConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId    string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_owlmq_owlmq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{4}
}

func (x *ConsumeRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageUuid   string                 `protobuf:"bytes,1,opt,name=message_uuid,json=messageUuid,proto3" json:"message_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_owlmq_owlmq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{5}
}

func (x *AckRequest) GetMessageUuid() string {
	if x != nil {
		return x.MessageUuid
	}
	return ""
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        MESSAGE_STATUS         `protobuf:"varint,1,opt,name=status,proto3,enum=api_owlmq.MESSAGE_STATUS" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_owlmq_owlmq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{6}
}

func (x *AckResponse) GetStatus() MESSAGE_STATUS {
	if x != nil {
		return x.Status
	}
	return MESSAGE_STATUS_MSG_SUCCESS
}

type NewQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewQueueRequest) Reset() {
	*x = NewQueueRequest{}
	mi := &file_owlmq_owlmq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewQueueRequest) ProtoMessage() {}

func (x *NewQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewQueueRequest.ProtoReflect.Descriptor instead.
func (*NewQueueRequest) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{7}
}

func (x *NewQueueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type NewQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        MESSAGE_STATUS         `protobuf:"varint,1,opt,name=status,proto3,enum=api_owlmq.MESSAGE_STATUS" json:"status,omitempty"` //TODO maybe add an error field for the error text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewQueueResponse) Reset() {
	*x = NewQueueResponse{}
	mi := &file_owlmq_owlmq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewQueueResponse) ProtoMessage() {}

func (x *NewQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewQueueResponse.ProtoReflect.Descriptor instead.
func (*NewQueueResponse) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{8}
}

func (x *NewQueueResponse) GetStatus() MESSAGE_STATUS {
	if x != nil {
		return x.Status
	}
	return MESSAGE_STATUS_MSG_SUCCESS
}

// ##################
// ###   cluster  ###
// ##################
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_owlmq_owlmq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{9}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_owlmq_owlmq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{10}
}

type NodeJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeJoinRequest) Reset() {
	*x = NodeJoinRequest{}
	mi := &file_owlmq_owlmq_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeJoinRequest) ProtoMessage() {}

func (x *NodeJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeJoinRequest.ProtoReflect.Descriptor instead.
func (*NodeJoinRequest) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{11}
}

func (x *NodeJoinRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type NodeJoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        NODEJOIN_STATUS        `protobuf:"varint,1,opt,name=status,proto3,enum=api_owlmq.NODEJOIN_STATUS" json:"status,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeJoinResponse) Reset() {
	*x = NodeJoinResponse{}
	mi := &file_owlmq_owlmq_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeJoinResponse) ProtoMessage() {}

func (x *NodeJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeJoinResponse.ProtoReflect.Descriptor instead.
func (*NodeJoinResponse) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{12}
}

func (x *NodeJoinResponse) GetStatus() NODEJOIN_STATUS {
	if x != nil {
		return x.Status
	}
	return NODEJOIN_STATUS_NJ_SUCCESS
}

func (x *NodeJoinResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type NodeListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeListRequest) Reset() {
	*x = NodeListRequest{}
	mi := &file_owlmq_owlmq_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeListRequest) ProtoMessage() {}

func (x *NodeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeListRequest.ProtoReflect.Descriptor instead.
func (*NodeListRequest) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{13}
}

type NodeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Successor     string                 `protobuf:"bytes,1,opt,name=successor,proto3" json:"successor,omitempty"`
	Predecessor   string                 `protobuf:"bytes,2,opt,name=predecessor,proto3" json:"predecessor,omitempty"`
	KnownNodes    []string               `protobuf:"bytes,3,rep,name=knownNodes,proto3" json:"knownNodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeListResponse) Reset() {
	*x = NodeListResponse{}
	mi := &file_owlmq_owlmq_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeListResponse) ProtoMessage() {}

func (x *NodeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeListResponse.ProtoReflect.Descriptor instead.
func (*NodeListResponse) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{14}
}

func (x *NodeListResponse) GetSuccessor() string {
	if x != nil {
		return x.Successor
	}
	return ""
}

func (x *NodeListResponse) GetPredecessor() string {
	if x != nil {
		return x.Predecessor
	}
	return ""
}

func (x *NodeListResponse) GetKnownNodes() []string {
	if x != nil {
		return x.KnownNodes
	}
	return nil
}

type FindSuccessorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSuccessorRequest) Reset() {
	*x = FindSuccessorRequest{}
	mi := &file_owlmq_owlmq_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSuccessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorRequest) ProtoMessage() {}

func (x *FindSuccessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorRequest.ProtoReflect.Descriptor instead.
func (*FindSuccessorRequest) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{15}
}

func (x *FindSuccessorRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type FindSuccessorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSuccessorResponse) Reset() {
	*x = FindSuccessorResponse{}
	mi := &file_owlmq_owlmq_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSuccessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorResponse) ProtoMessage() {}

func (x *FindSuccessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorResponse.ProtoReflect.Descriptor instead.
func (*FindSuccessorResponse) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{16}
}

func (x *FindSuccessorResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetPredecessorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredecessorRequest) Reset() {
	*x = GetPredecessorRequest{}
	mi := &file_owlmq_owlmq_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredecessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredecessorRequest) ProtoMessage() {}

func (x *GetPredecessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredecessorRequest.ProtoReflect.Descriptor instead.
func (*GetPredecessorRequest) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{17}
}

type GetPredecessorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPredecessorResponse) Reset() {
	*x = GetPredecessorResponse{}
	mi := &file_owlmq_owlmq_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPredecessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredecessorResponse) ProtoMessage() {}

func (x *GetPredecessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredecessorResponse.ProtoReflect.Descriptor instead.
func (*GetPredecessorResponse) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{18}
}

func (x *GetPredecessorResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetSuccessorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSuccessorRequest) Reset() {
	*x = GetSuccessorRequest{}
	mi := &file_owlmq_owlmq_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSuccessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuccessorRequest) ProtoMessage() {}

func (x *GetSuccessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuccessorRequest.ProtoReflect.Descriptor instead.
func (*GetSuccessorRequest) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{19}
}

type GetSuccessorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSuccessorResponse) Reset() {
	*x = GetSuccessorResponse{}
	mi := &file_owlmq_owlmq_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSuccessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuccessorResponse) ProtoMessage() {}

func (x *GetSuccessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuccessorResponse.ProtoReflect.Descriptor instead.
func (*GetSuccessorResponse) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{20}
}

func (x *GetSuccessorResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type SetPredecessorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPredecessorRequest) Reset() {
	*x = SetPredecessorRequest{}
	mi := &file_owlmq_owlmq_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPredecessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPredecessorRequest) ProtoMessage() {}

func (x *SetPredecessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPredecessorRequest.ProtoReflect.Descriptor instead.
func (*SetPredecessorRequest) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{21}
}

func (x *SetPredecessorRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type SetPredecessorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPredecessorResponse) Reset() {
	*x = SetPredecessorResponse{}
	mi := &file_owlmq_owlmq_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPredecessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPredecessorResponse) ProtoMessage() {}

func (x *SetPredecessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPredecessorResponse.ProtoReflect.Descriptor instead.
func (*SetPredecessorResponse) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{22}
}

type SetSuccessorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSuccessorRequest) Reset() {
	*x = SetSuccessorRequest{}
	mi := &file_owlmq_owlmq_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSuccessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSuccessorRequest) ProtoMessage() {}

func (x *SetSuccessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSuccessorRequest.ProtoReflect.Descriptor instead.
func (*SetSuccessorRequest) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{23}
}

func (x *SetSuccessorRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type SetSuccessorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSuccessorResponse) Reset() {
	*x = SetSuccessorResponse{}
	mi := &file_owlmq_owlmq_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSuccessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSuccessorResponse) ProtoMessage() {}

func (x *SetSuccessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSuccessorResponse.ProtoReflect.Descriptor instead.
func (*SetSuccessorResponse) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{24}
}

type ReplicatedEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	OwnerAddress  string                 `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicatedEntry) Reset() {
	*x = ReplicatedEntry{}
	mi := &file_owlmq_owlmq_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicatedEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicatedEntry) ProtoMessage() {}

func (x *ReplicatedEntry) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicatedEntry.ProtoReflect.Descriptor instead.
func (*ReplicatedEntry) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{25}
}

func (x *ReplicatedEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ReplicatedEntry) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *ReplicatedEntry) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type ReplicaGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaGetRequest) Reset() {
	*x = ReplicaGetRequest{}
	mi := &file_owlmq_owlmq_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaGetRequest) ProtoMessage() {}

func (x *ReplicaGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaGetRequest.ProtoReflect.Descriptor instead.
func (*ReplicaGetRequest) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{26}
}

func (x *ReplicaGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ReplicaGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        REPLICA_STATUS         `protobuf:"varint,1,opt,name=status,proto3,enum=api_owlmq.REPLICA_STATUS" json:"status,omitempty"`
	Value         *ReplicatedEntry       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaGetResponse) Reset() {
	*x = ReplicaGetResponse{}
	mi := &file_owlmq_owlmq_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaGetResponse) ProtoMessage() {}

func (x *ReplicaGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaGetResponse.ProtoReflect.Descriptor instead.
func (*ReplicaGetResponse) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{27}
}

func (x *ReplicaGetResponse) GetStatus() REPLICA_STATUS {
	if x != nil {
		return x.Status
	}
	return REPLICA_STATUS_REPLICA_SUCCESS
}

func (x *ReplicaGetResponse) GetValue() *ReplicatedEntry {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ReplicaGetResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ReplicaPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *ReplicatedEntry       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaPutRequest) Reset() {
	*x = ReplicaPutRequest{}
	mi := &file_owlmq_owlmq_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaPutRequest) ProtoMessage() {}

func (x *ReplicaPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaPutRequest.ProtoReflect.Descriptor instead.
func (*ReplicaPutRequest) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{28}
}

func (x *ReplicaPutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReplicaPutRequest) GetValue() *ReplicatedEntry {
	if x != nil {
		return x.Value
	}
	return nil
}

type ReplicaPutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        REPLICA_STATUS         `protobuf:"varint,1,opt,name=status,proto3,enum=api_owlmq.REPLICA_STATUS" json:"status,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaPutResponse) Reset() {
	*x = ReplicaPutResponse{}
	mi := &file_owlmq_owlmq_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaPutResponse) ProtoMessage() {}

func (x *ReplicaPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaPutResponse.ProtoReflect.Descriptor instead.
func (*ReplicaPutResponse) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{29}
}

func (x *ReplicaPutResponse) GetStatus() REPLICA_STATUS {
	if x != nil {
		return x.Status
	}
	return REPLICA_STATUS_REPLICA_SUCCESS
}

func (x *ReplicaPutResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type KV_GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KV_GetRequest) Reset() {
	*x = KV_GetRequest{}
	mi := &file_owlmq_owlmq_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KV_GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KV_GetRequest) ProtoMessage() {}

func (x *KV_GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KV_GetRequest.ProtoReflect.Descriptor instead.
func (*KV_GetRequest) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{30}
}

func (x *KV_GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KV_GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        KV_STATUS              `protobuf:"varint,1,opt,name=status,proto3,enum=api_owlmq.KV_STATUS" json:"status,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KV_GetResponse) Reset() {
	*x = KV_GetResponse{}
	mi := &file_owlmq_owlmq_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KV_GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KV_GetResponse) ProtoMessage() {}

func (x *KV_GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KV_GetResponse.ProtoReflect.Descriptor instead.
func (*KV_GetResponse) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{31}
}

func (x *KV_GetResponse) GetStatus() KV_STATUS {
	if x != nil {
		return x.Status
	}
	return KV_STATUS_KV_SUCCESS
}

func (x *KV_GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *KV_GetResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type KV_PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KV_PutRequest) Reset() {
	*x = KV_PutRequest{}
	mi := &file_owlmq_owlmq_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KV_PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KV_PutRequest) ProtoMessage() {}

func (x *KV_PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KV_PutRequest.ProtoReflect.Descriptor instead.
func (*KV_PutRequest) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{32}
}

func (x *KV_PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KV_PutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type KV_PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        KV_STATUS              `protobuf:"varint,1,opt,name=status,proto3,enum=api_owlmq.KV_STATUS" json:"status,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KV_PutResponse) Reset() {
	*x = KV_PutResponse{}
	mi := &file_owlmq_owlmq_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KV_PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KV_PutResponse) ProtoMessage() {}

func (x *KV_PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owlmq_owlmq_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KV_PutResponse.ProtoReflect.Descriptor instead.
func (*KV_PutResponse) Descriptor() ([]byte, []int) {
	return file_owlmq_owlmq_proto_rawDescGZIP(), []int{33}
}

func (x *KV_PutResponse) GetStatus() KV_STATUS {
	if x != nil {
		return x.Status
	}
	return KV_STATUS_KV_SUCCESS
}

func (x *KV_PutResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_owlmq_owlmq_proto protoreflect.FileDescriptor

var file_owlmq_owlmq_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x37, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x47, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x65, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19,
	0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4d, 0x45, 0x53, 0x53, 0x41,
	0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x44, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71,
	0x2e, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x34, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b,
	0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x22, 0x31, 0x0a,
	0x0e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x2f, 0x0a, 0x0a, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x75, 0x69,
	0x64, 0x22, 0x40, 0x0a, 0x0b, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4d, 0x45, 0x53,
	0x53, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x30, 0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x45, 0x0a, 0x10, 0x4e, 0x65, 0x77, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x5f,
	0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x0d, 0x0a, 0x0b,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2b, 0x0a, 0x0f, 0x4e,
	0x6f, 0x64, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x62, 0x0a, 0x10, 0x4e, 0x6f, 0x64, 0x65,
	0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x61,
	0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4e, 0x4f, 0x44, 0x45, 0x4a, 0x4f, 0x49,
	0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x11, 0x0a, 0x0f,
	0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x72, 0x0a, 0x10, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x4e, 0x6f, 0x64, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x4e, 0x6f,
	0x64, 0x65, 0x73, 0x22, 0x2a, 0x0a, 0x14, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22,
	0x31, 0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x30, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x31, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x50,
	0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x53,
	0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2f, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x8b,
	0x01, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x3d, 0x0a,
	0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x25, 0x0a, 0x11,
	0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x22, 0x95, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69,
	0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x52, 0x45, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x30, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61,
	0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x57, 0x0a, 0x11, 0x52,
	0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x30, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x52, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x63, 0x0a, 0x12, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x50,
	0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69,
	0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x52, 0x45, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x21, 0x0a, 0x0d, 0x4b, 0x56, 0x5f,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x70, 0x0a, 0x0e,
	0x4b, 0x56, 0x5f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14,
	0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4b, 0x56, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x37,
	0x0a, 0x0d, 0x4b, 0x56, 0x5f, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x5a, 0x0a, 0x0e, 0x4b, 0x56, 0x5f, 0x50, 0x75,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x5f,
	0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4b, 0x56, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x2a, 0x32, 0x0a, 0x0e, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x53, 0x47, 0x5f, 0x53, 0x55, 0x43,
	0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x53, 0x47, 0x5f, 0x46, 0x41,
	0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x01, 0x2a, 0x31, 0x0a, 0x0f, 0x4e, 0x4f, 0x44, 0x45, 0x4a,
	0x4f, 0x49, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x4a,
	0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x4a,
	0x5f, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x01, 0x2a, 0x3a, 0x0a, 0x0e, 0x52, 0x45,
	0x50, 0x4c, 0x49, 0x43, 0x41, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x12, 0x13, 0x0a, 0x0f,
	0x52, 0x45, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10,
	0x00, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x5f, 0x46, 0x41, 0x49,
	0x4c, 0x55, 0x52, 0x45, 0x10, 0x01, 0x2a, 0x2b, 0x0a, 0x09, 0x4b, 0x56, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x12, 0x0e, 0x0a, 0x0a, 0x4b, 0x56, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53,
	0x53, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4b, 0x56, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52,
	0x45, 0x10, 0x01, 0x32, 0xfb, 0x09, 0x0a, 0x05, 0x4f, 0x77, 0x6c, 0x6d, 0x71, 0x12, 0x43, 0x0a,
	0x08, 0x4e, 0x6f, 0x64, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x5f,
	0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d,
	0x71, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a,
	0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69,
	0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x64, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f,
	0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x5f,
	0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x04, 0x50,
	0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70,
	0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x65,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c,
	0x6d, 0x71, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f,
	0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x1e, 0x2e, 0x61, 0x70,
	0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70,
	0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x0e,
	0x53, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x20,
	0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x53, 0x65, 0x74, 0x50, 0x72,
	0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x53, 0x65, 0x74,
	0x50, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e,
	0x53, 0x65, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e,
	0x53, 0x65, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77,
	0x6c, 0x6d, 0x71, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d,
	0x71, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0f, 0x50, 0x75, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77,
	0x6c, 0x6d, 0x71, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x50, 0x75, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d,
	0x71, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x18, 0x2e, 0x61, 0x70,
	0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4b, 0x56, 0x5f, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d,
	0x71, 0x2e, 0x4b, 0x56, 0x5f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3a, 0x0a, 0x03, 0x50, 0x75, 0x74, 0x12, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77,
	0x6c, 0x6d, 0x71, 0x2e, 0x4b, 0x56, 0x5f, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4b, 0x56,
	0x5f, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0a,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x4f, 0x6e, 0x65, 0x12, 0x12, 0x2e, 0x61, 0x70, 0x69,
	0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1d,
	0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x65, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a,
	0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x12, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f,
	0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1a, 0x2e, 0x61,
	0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x3e, 0x0a, 0x0a, 0x43, 0x6f,
	0x6e, 0x73, 0x75, 0x6d, 0x65, 0x4f, 0x6e, 0x65, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f,
	0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x4f, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c,
	0x6d, 0x71, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d,
	0x71, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x30, 0x01, 0x12, 0x43, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4e,
	0x65, 0x77, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x4e, 0x65, 0x77, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x03, 0x41,
	0x63, 0x6b, 0x12, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x41,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x5f,
	0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x2e, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x6f, 0x77, 0x6c, 0x6d, 0x71, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_owlmq_owlmq_proto_rawDescOnce sync.Once
	file_owlmq_owlmq_proto_rawDescData = file_owlmq_owlmq_proto_rawDesc
)

func file_owlmq_owlmq_proto_rawDescGZIP() []byte {
	file_owlmq_owlmq_proto_rawDescOnce.Do(func() {
		file_owlmq_owlmq_proto_rawDescData = protoimpl.X.CompressGZIP(file_owlmq_owlmq_proto_rawDescData)
	})
	return file_owlmq_owlmq_proto_rawDescData
}

var file_owlmq_owlmq_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_owlmq_owlmq_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_owlmq_owlmq_proto_goTypes = []any{
	(MESSAGE_STATUS)(0),            // 0: api_owlmq.MESSAGE_STATUS
	(NODEJOIN_STATUS)(0),           // 1: api_owlmq.NODEJOIN_STATUS
	(REPLICA_STATUS)(0),            // 2: api_owlmq.REPLICA_STATUS
	(KV_STATUS)(0),                 // 3: api_owlmq.KV_STATUS
	(*Message)(nil),                // 4: api_owlmq.Message
	(*ProduceOneResponse)(nil),     // 5: api_owlmq.ProduceOneResponse
	(*ProduceResponse)(nil),        // 6: api_owlmq.ProduceResponse
	(*ConsumeOneRequest)(nil),      // 7: api_owlmq.ConsumeOneRequest
	(*ConsumeRequest)(nil),         // 8: api_owlmq.ConsumeRequest
	(*AckRequest)(nil),             // 9: api_owlmq.AckRequest
	(*AckResponse)(nil),            // 10: api_owlmq.AckResponse
	(*NewQueueRequest)(nil),        // 11: api_owlmq.NewQueueRequest
	(*NewQueueResponse)(nil),       // 12: api_owlmq.NewQueueResponse
	(*PingRequest)(nil),            // 13: api_owlmq.PingRequest
	(*PingResponse)(nil),           // 14: api_owlmq.PingResponse
	(*NodeJoinRequest)(nil),        // 15: api_owlmq.NodeJoinRequest
	(*NodeJoinResponse)(nil),       // 16: api_owlmq.NodeJoinResponse
	(*NodeListRequest)(nil),        // 17: api_owlmq.NodeListRequest
	(*NodeListResponse)(nil),       // 18: api_owlmq.NodeListResponse
	(*FindSuccessorRequest)(nil),   // 19: api_owlmq.FindSuccessorRequest
	(*FindSuccessorResponse)(nil),  // 20: api_owlmq.FindSuccessorResponse
	(*GetPredecessorRequest)(nil),  // 21: api_owlmq.GetPredecessorRequest
	(*GetPredecessorResponse)(nil), // 22: api_owlmq.GetPredecessorResponse
	(*GetSuccessorRequest)(nil),    // 23: api_owlmq.GetSuccessorRequest
	(*GetSuccessorResponse)(nil),   // 24: api_owlmq.GetSuccessorResponse
	(*SetPredecessorRequest)(nil),  // 25: api_owlmq.SetPredecessorRequest
	(*SetPredecessorResponse)(nil), // 26: api_owlmq.SetPredecessorResponse
	(*SetSuccessorRequest)(nil),    // 27: api_owlmq.SetSuccessorRequest
	(*SetSuccessorResponse)(nil),   // 28: api_owlmq.SetSuccessorResponse
	(*ReplicatedEntry)(nil),        // 29: api_owlmq.ReplicatedEntry
	(*ReplicaGetRequest)(nil),      // 30: api_owlmq.ReplicaGetRequest
	(*ReplicaGetResponse)(nil),     // 31: api_owlmq.ReplicaGetResponse
	(*ReplicaPutRequest)(nil),      // 32: api_owlmq.ReplicaPutRequest
	(*ReplicaPutResponse)(nil),     // 33: api_owlmq.ReplicaPutResponse
	(*KV_GetRequest)(nil),          // 34: api_owlmq.KV_GetRequest
	(*KV_GetResponse)(nil),         // 35: api_owlmq.KV_GetResponse
	(*KV_PutRequest)(nil),          // 36: api_owlmq.KV_PutRequest
	(*KV_PutResponse)(nil),         // 37: api_owlmq.KV_PutResponse
	(*timestamppb.Timestamp)(nil),  // 38: google.protobuf.Timestamp
}
var file_owlmq_owlmq_proto_depIdxs = []int32{
	0,  // 0: api_owlmq.ProduceOneResponse.status:type_name -> api_owlmq.MESSAGE_STATUS
	0,  // 1: api_owlmq.ProduceResponse.status:type_name -> api_owlmq.MESSAGE_STATUS
	0,  // 2: api_owlmq.AckResponse.status:type_name -> api_owlmq.MESSAGE_STATUS
	0,  // 3: api_owlmq.NewQueueResponse.status:type_name -> api_owlmq.MESSAGE_STATUS
	1,  // 4: api_owlmq.NodeJoinResponse.status:type_name -> api_owlmq.NODEJOIN_STATUS
	38, // 5: api_owlmq.ReplicatedEntry.last_updated:type_name -> google.protobuf.Timestamp
	2,  // 6: api_owlmq.ReplicaGetResponse.status:type_name -> api_owlmq.REPLICA_STATUS
	29, // 7: api_owlmq.ReplicaGetResponse.value:type_name -> api_owlmq.ReplicatedEntry
	29, // 8: api_owlmq.ReplicaPutRequest.value:type_name -> api_owlmq.ReplicatedEntry
	2,  // 9: api_owlmq.ReplicaPutResponse.status:type_name -> api_owlmq.REPLICA_STATUS
	3,  // 10: api_owlmq.KV_GetResponse.status:type_name -> api_owlmq.KV_STATUS
	3,  // 11: api_owlmq.KV_PutResponse.status:type_name -> api_owlmq.KV_STATUS
	15, // 12: api_owlmq.Owlmq.NodeJoin:input_type -> api_owlmq.NodeJoinRequest
	17, // 13: api_owlmq.Owlmq.NodeList:input_type -> api_owlmq.NodeListRequest
	19, // 14: api_owlmq.Owlmq.FindSuccessor:input_type -> api_owlmq.FindSuccessorRequest
	13, // 15: api_owlmq.Owlmq.Ping:input_type -> api_owlmq.PingRequest
	21, // 16: api_owlmq.Owlmq.GetPredecessor:input_type -> api_owlmq.GetPredecessorRequest
	23, // 17: api_owlmq.Owlmq.GetSuccessor:input_type -> api_owlmq.GetSuccessorRequest
	25, // 18: api_owlmq.Owlmq.SetPredecessor:input_type -> api_owlmq.SetPredecessorRequest
	27, // 19: api_owlmq.Owlmq.SetSuccessor:input_type -> api_owlmq.SetSuccessorRequest
	30, // 20: api_owlmq.Owlmq.GetReplicaEntry:input_type -> api_owlmq.ReplicaGetRequest
	32, // 21: api_owlmq.Owlmq.PutReplicaEntry:input_type -> api_owlmq.ReplicaPutRequest
	34, // 22: api_owlmq.Owlmq.Get:input_type -> api_owlmq.KV_GetRequest
	36, // 23: api_owlmq.Owlmq.Put:input_type -> api_owlmq.KV_PutRequest
	4,  // 24: api_owlmq.Owlmq.ProduceOne:input_type -> api_owlmq.Message
	4,  // 25: api_owlmq.Owlmq.Produce:input_type -> api_owlmq.Message
	7,  // 26: api_owlmq.Owlmq.ConsumeOne:input_type -> api_owlmq.ConsumeOneRequest
	8,  // 27: api_owlmq.Owlmq.Consume:input_type -> api_owlmq.ConsumeRequest
	11, // 28: api_owlmq.Owlmq.NewQueue:input_type -> api_owlmq.NewQueueRequest
	9,  // 29: api_owlmq.Owlmq.Ack:input_type -> api_owlmq.AckRequest
	16, // 30: api_owlmq.Owlmq.NodeJoin:output_type -> api_owlmq.NodeJoinResponse
	18, // 31: api_owlmq.Owlmq.NodeList:output_type -> api_owlmq.NodeListResponse
	20, // 32: api_owlmq.Owlmq.FindSuccessor:output_type -> api_owlmq.FindSuccessorResponse
	14, // 33: api_owlmq.Owlmq.Ping:output_type -> api_owlmq.PingResponse
	22, // 34: api_owlmq.Owlmq.GetPredecessor:output_type -> api_owlmq.GetPredecessorResponse
	24, // 35: api_owlmq.Owlmq.GetSuccessor:output_type -> api_owlmq.GetSuccessorResponse
	26, // 36: api_owlmq.Owlmq.SetPredecessor:output_type -> api_owlmq.SetPredecessorResponse
	28, // 37: api_owlmq.Owlmq.SetSuccessor:output_type -> api_owlmq.SetSuccessorResponse
	31, // 38: api_owlmq.Owlmq.GetReplicaEntry:output_type -> api_owlmq.ReplicaGetResponse
	33, // 39: api_owlmq.Owlmq.PutReplicaEntry:output_type -> api_owlmq.ReplicaPutResponse
	35, // 40: api_owlmq.Owlmq.Get:output_type -> api_owlmq.KV_GetResponse
	37, // 41: api_owlmq.Owlmq.Put:output_type -> api_owlmq.KV_PutResponse
	5,  // 42: api_owlmq.Owlmq.ProduceOne:output_type -> api_owlmq.ProduceOneResponse
	6,  // 43: api_owlmq.Owlmq.Produce:output_type -> api_owlmq.ProduceResponse
	4,  // 44: api_owlmq.Owlmq.ConsumeOne:output_type -> api_owlmq.Message
	4,  // 45: api_owlmq.Owlmq.Consume:output_type -> api_owlmq.Message
	12, // 46: api_owlmq.Owlmq.NewQueue:output_type -> api_owlmq.NewQueueResponse
	10, // 47: api_owlmq.Owlmq.Ack:output_type -> api_owlmq.AckResponse
	30, // [30:48] is the sub-list for method output_type
	12, // [12:30] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_owlmq_owlmq_proto_init() }
func file_owlmq_owlmq_proto_init() {
	if File_owlmq_owlmq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_owlmq_owlmq_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_owlmq_owlmq_proto_goTypes,
		DependencyIndexes: file_owlmq_owlmq_proto_depIdxs,
		EnumInfos:         file_owlmq_owlmq_proto_enumTypes,
		MessageInfos:      file_owlmq_owlmq_proto_msgTypes,
	}.Build()
	File_owlmq_owlmq_proto = out.File
	file_owlmq_owlmq_proto_rawDesc = nil
	file_owlmq_owlmq_proto_goTypes = nil
	file_owlmq_owlmq_proto_depIdxs = nil
}
