// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: owlmq/owlmq.proto

package owlmq

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Owlmq_NodeList_FullMethodName      = "/api_owlmq.Owlmq/NodeList"
	Owlmq_FindSuccessor_FullMethodName = "/api_owlmq.Owlmq/FindSuccessor"
	Owlmq_Get_FullMethodName           = "/api_owlmq.Owlmq/Get"
	Owlmq_Put_FullMethodName           = "/api_owlmq.Owlmq/Put"
)

// OwlmqClient is the client API for Owlmq service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OwlmqClient interface {
	// ##################
	// ###   cluster  ###
	// ##################
	// rpc NodeJoin() returns () {
	// option (components.rbac.v1.access_control) = {
	// allowed_roles: [ROLE_NODE]
	// allow_unauthenticated: false
	// };
	// };
	// rpc NodeJoin() returns ();
	// rpc NodeLeave() returns ();
	NodeList(ctx context.Context, in *NodeListRequest, opts ...grpc.CallOption) (*NodeListResponse, error)
	FindSuccessor(ctx context.Context, in *FindSuccessorRequest, opts ...grpc.CallOption) (*FindSuccessorResponse, error)
	// ##############################
	// ###    key-value store     ###
	// ##############################
	Get(ctx context.Context, in *KV_GetRequest, opts ...grpc.CallOption) (*KV_GetResponse, error)
	Put(ctx context.Context, in *KV_PutRequest, opts ...grpc.CallOption) (*KV_PutResponse, error)
}

type owlmqClient struct {
	cc grpc.ClientConnInterface
}

func NewOwlmqClient(cc grpc.ClientConnInterface) OwlmqClient {
	return &owlmqClient{cc}
}

func (c *owlmqClient) NodeList(ctx context.Context, in *NodeListRequest, opts ...grpc.CallOption) (*NodeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeListResponse)
	err := c.cc.Invoke(ctx, Owlmq_NodeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlmqClient) FindSuccessor(ctx context.Context, in *FindSuccessorRequest, opts ...grpc.CallOption) (*FindSuccessorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindSuccessorResponse)
	err := c.cc.Invoke(ctx, Owlmq_FindSuccessor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlmqClient) Get(ctx context.Context, in *KV_GetRequest, opts ...grpc.CallOption) (*KV_GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KV_GetResponse)
	err := c.cc.Invoke(ctx, Owlmq_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owlmqClient) Put(ctx context.Context, in *KV_PutRequest, opts ...grpc.CallOption) (*KV_PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KV_PutResponse)
	err := c.cc.Invoke(ctx, Owlmq_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OwlmqServer is the server API for Owlmq service.
// All implementations must embed UnimplementedOwlmqServer
// for forward compatibility.
type OwlmqServer interface {
	// ##################
	// ###   cluster  ###
	// ##################
	// rpc NodeJoin() returns () {
	// option (components.rbac.v1.access_control) = {
	// allowed_roles: [ROLE_NODE]
	// allow_unauthenticated: false
	// };
	// };
	// rpc NodeJoin() returns ();
	// rpc NodeLeave() returns ();
	NodeList(context.Context, *NodeListRequest) (*NodeListResponse, error)
	FindSuccessor(context.Context, *FindSuccessorRequest) (*FindSuccessorResponse, error)
	// ##############################
	// ###    key-value store     ###
	// ##############################
	Get(context.Context, *KV_GetRequest) (*KV_GetResponse, error)
	Put(context.Context, *KV_PutRequest) (*KV_PutResponse, error)
	mustEmbedUnimplementedOwlmqServer()
}

// UnimplementedOwlmqServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOwlmqServer struct{}

func (UnimplementedOwlmqServer) NodeList(context.Context, *NodeListRequest) (*NodeListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeList not implemented")
}
func (UnimplementedOwlmqServer) FindSuccessor(context.Context, *FindSuccessorRequest) (*FindSuccessorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindSuccessor not implemented")
}
func (UnimplementedOwlmqServer) Get(context.Context, *KV_GetRequest) (*KV_GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedOwlmqServer) Put(context.Context, *KV_PutRequest) (*KV_PutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedOwlmqServer) mustEmbedUnimplementedOwlmqServer() {}
func (UnimplementedOwlmqServer) testEmbeddedByValue()               {}

// UnsafeOwlmqServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OwlmqServer will
// result in compilation errors.
type UnsafeOwlmqServer interface {
	mustEmbedUnimplementedOwlmqServer()
}

func RegisterOwlmqServer(s grpc.ServiceRegistrar, srv OwlmqServer) {
	// If the following call pancis, it indicates UnimplementedOwlmqServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Owlmq_ServiceDesc, srv)
}

func _Owlmq_NodeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).NodeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_NodeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).NodeList(ctx, req.(*NodeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Owlmq_FindSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindSuccessorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).FindSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_FindSuccessor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).FindSuccessor(ctx, req.(*FindSuccessorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Owlmq_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KV_GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).Get(ctx, req.(*KV_GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Owlmq_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KV_PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwlmqServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Owlmq_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwlmqServer).Put(ctx, req.(*KV_PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Owlmq_ServiceDesc is the grpc.ServiceDesc for Owlmq service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Owlmq_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api_owlmq.Owlmq",
	HandlerType: (*OwlmqServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NodeList",
			Handler:    _Owlmq_NodeList_Handler,
		},
		{
			MethodName: "FindSuccessor",
			Handler:    _Owlmq_FindSuccessor_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Owlmq_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Owlmq_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "owlmq/owlmq.proto",
}
