syntax = "proto3";
//import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
option go_package  = "/owlmq";
package api_owlmq;

// This file holds the description of the outside api of owlmq
//enum Role {
  //ROLE_NOROLE = 0;
  //ROLE_USER = 1;
  //ROLE_NODE = 2;
  //ROLE_ADMIN = 3;
//}

//message RoleBasedAccessControl {
  //repeated Role allowed_roles = 1;
  //bool allow_unauthenticated = 2;
//}

//extend google.protobuf.MethodOptions {
  //optional RoleBasedAccessControl access_control = 90000;
//}

service Owlmq {
  //##################
  //###   cluster  ###
  //##################
  //rpc NodeJoin() returns () {
    //option (components.rbac.v1.access_control) = {
      //allowed_roles: [ROLE_NODE]
      //allow_unauthenticated: false
    //};
  //};
  rpc NodeJoin(NodeJoinRequest) returns (NodeJoinResponse);
  //rpc NodeLeave() returns ();
  rpc NodeList(NodeListRequest) returns (NodeListResponse);
  rpc FindSuccessor(FindSuccessorRequest) returns (FindSuccessorResponse);

  rpc Ping(PingRequest) returns (PingResponse);
  rpc GetPredecessor(GetPredecessorRequest) returns (GetPredecessorResponse);
  rpc GetSuccessor(GetSuccessorRequest) returns (GetSuccessorResponse);
  rpc SetPredecessor(SetPredecessorRequest) returns (SetPredecessorResponse);
  rpc SetSuccessor(SetSuccessorRequest) returns (SetSuccessorResponse);

  //###################
  //###    auth     ###
  //###################
  //rpc UserRegister() returns ();
  //rpc UserDelete() returns ();
  //rpc UserList() returns ();

  //##############################
  //###      replication       ###
  //##############################
  rpc GetReplicaEntry(ReplicaGetRequest) returns (ReplicaGetResponse);
  rpc PutReplicaEntry(ReplicaPutRequest) returns (ReplicaPutResponse);

  //##############################
  //###    key-value store     ###
  //##############################
  rpc Get(KV_GetRequest) returns (KV_GetResponse);
  rpc Put(KV_PutRequest) returns (KV_PutResponse);

  //##############################
  //###       messaging        ###
  //##############################
  rpc ProduceOne(Message) returns (ProduceOneResponse);
  rpc Produce(stream Message) returns (ProduceResponse);
  rpc ConsumeOne(ConsumeOneRequest) returns (Message);
  rpc Consume(ConsumeRequest) returns (stream Message);
  rpc NewQueue(NewQueueRequest) returns (NewQueueResponse);
  rpc Ack(AckRequest) returns (AckResponse);
}
//##################
//###  messaging ###
//##################
enum MESSAGE_STATUS {
  MSG_SUCCESS = 0;
  MSG_FAILURE = 1;
}

message Message {
  //TODO think about this, could be nice so that the user can set the id -> storage location on the ring
  string queue_name = 1;
  string content = 2;
  //TODO string exchange = 3;
}

//TODO think about a way to put the queue name here and maybe not into the message
message ProduceOneResponse {
  MESSAGE_STATUS status = 1;
}

message ProduceResponse {
  MESSAGE_STATUS status = 1;
}

message ConsumeOneRequest {
  string queue_name = 1;
  string consumer_group = 2;
}

message ConsumeRequest {
  string queue_name = 1;
  string consumer_group = 2;
}

message AckRequest {
  string message_uuid = 1;
}

message AckResponse {
  MESSAGE_STATUS status = 1;
}

message NewQueueRequest {
  string queue_name = 1;
}

message NewQueueResponse {
  MESSAGE_STATUS status = 1;
  //TODO maybe add an error field for the error text
}

//##################
//###   cluster  ###
//##################
message PingRequest {}
message PingResponse {}

enum NODEJOIN_STATUS {
  NJ_SUCCESS = 0;
  NJ_FAILURE = 1;
}
message NodeJoinRequest { string address = 1; }
message NodeJoinResponse {
  NODEJOIN_STATUS status = 1;
  string errorMsg = 2;
}

message NodeListRequest {}

message NodeListResponse {
  string successor = 1;
  string predecessor = 2;
  repeated string knownNodes = 3;
}

message FindSuccessorRequest { bytes hash = 1; }
message FindSuccessorResponse { string address = 1; }

message GetPredecessorRequest {}
message GetPredecessorResponse { string address = 1; }

message GetSuccessorRequest {}
message GetSuccessorResponse { string address = 1; }

message SetPredecessorRequest { string address = 1; }
message SetPredecessorResponse {}

message SetSuccessorRequest { string address = 1; }
message SetSuccessorResponse {}

//##############################
//###      replication       ###
//##############################
enum REPLICA_STATUS {
  REPLICA_SUCCESS = 0;
  REPLICA_FAILURE = 1;
}

message ReplicatedEntry {
  string value = 1;
  string owner_address = 2;
  google.protobuf.Timestamp last_updated = 3;
}

message ReplicaGetRequest {
  string key = 1;
}

message ReplicaGetResponse {
  REPLICA_STATUS status = 1;
  ReplicatedEntry value = 2;
  string errorMsg = 3;
}

message ReplicaPutRequest {
  string key = 1;
  ReplicatedEntry value = 2;
}

message ReplicaPutResponse {
  REPLICA_STATUS status = 1;
  string errorMsg = 2;
}

//##############################
//###    key-value store     ###
//##############################
enum KV_STATUS {
  KV_SUCCESS = 0;
  KV_FAILURE = 1;
}

message KV_GetRequest {
  string key = 1;
}

message KV_GetResponse {
  KV_STATUS status = 1;
  string value = 2;
  string errorMsg = 3;
}

message KV_PutRequest {
  string key = 1;
  string value = 2;
}

message KV_PutResponse {
  KV_STATUS status = 1;
  string errorMsg = 2;
}
