import "google/protobuf/empty.proto";

syntax = "proto3";

package plugin;

service PluginService {
  rpc Connect(ConnectRequest) returns (ConnectResponse);
  rpc HealthCheck(google.protobuf.Empty) returns (stream google.protobuf.Empty);
}

//-------------------
// Connect is called by a program/user that wants to connect the Plugin with the database system
enum ConnectionStatus {
  ACCEPTED = 0;
  DENIED = 1;
}
message ConnectRequest {
  string plugin_name = 1;
  string connect_to_host = 2;
  string connect_to_password = 3;
}
message ConnectResponse {
  ConnectionStatus status = 1;
}
//-------------------
// HealthCheck is called by the database to see if the plugin is still up and running
message HealthCheckRequest {
  string input = 1;
}

message HealthCheckResponse {
  string output = 1;
}
