load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "web",
    srcs = [
        "cluster.go",
        "kv.go",
        "messaging.go",
        "queueworker.go",
        "web.go",
    ],
    importpath = "github.com/owlmq/owlmq/web",
    visibility = ["//visibility:public"],
    deps = [
        "//api/owlmq",
        "//chord",
        "//config",
        "//crypto",
        "//messaging",
        "//queueworker",
        "//replicator",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials/insecure",
        "@org_golang_google_protobuf//types/known/timestamppb",
    ],
)
